class SchoolSubmissionBaseSerializer < BaseSerializer

 attributes :id,
            :address_city,
            :address_one,
            :address_state,
            :address_zip,
            :contact_email,
            :contact_first_name,
            :contact_last_name,
            :contact_phone_number,
            :contact_title,
            :name,
            :student_address_city,
            :student_address_one,
            :student_address_state,
            :student_address_zip,
            :student_birthday,
            :student_cell_phone,
            :student_email,
            :student_first_name,
            :student_guardian_first_name,
            :student_guardian_email,
            :student_guardian_last_name,
            :student_guardian_phone_number,
            :student_guardian_phone_type,
            :student_guardian_relationship,
            :student_home_phone,
            :student_gender,
            :student_last_name,
            :student_shirt_size

end
