AllCops:
  Exclude:
    - 'bin/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
  TargetRubyVersion: 2.2

Documentation:
    Enabled: false

Metrics/ClassLength:
  CountComments: false
  Max: 200

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 100

Rails:
  Enabled: true

Rails/Output:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
