AllCops:
  Exclude:
    - 'bin/*'
    - 'config/application.rb'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
  TargetRubyVersion: 2.2

Documentation:
    Enabled: false

Rails/FindBy:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/ClassLength:
  CountComments: false
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 100

Metrics/PerceivedComplexity:
  Max: 20

Performance/Detect:
  Enabled: false

Rails:
  Enabled: true

Rails/Delegate:
  Enabled: false

Rails/Output:
  Enabled: false

SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

