class StudentSubmissionBaseSerializer < BaseSerializer

  attributes :id,
             :address_city,
             :address_one,
             :address_state,
             :address_two,
             :address_zip,
             :allergies,
             :birthday,
             :cell_phone,
             :current_page,
             :dietary_restrictions,
             :email,
             :emergency_consent,
             :exercise_limitations,
             :first_name,
             :gender,
             :guardian_one_email,
             :guardian_one_employer,
             :guardian_one_first_name,
             :guardian_one_job_title,
             :guardian_one_last_name,
             :guardian_one_phone_number,
             :guardian_one_phone_type,
             :guardian_one_relationship,
             :health_conditions,
             :home_phone,
             :is_active,
             :immunizations,
             :last_name,
             :medical_guardian_name,
             :medications,
             :other_dietary_restrictions,
             :preferred_name,
             :psychologist_consent,
             :shirt_size

end
