development: &default
  adapter:   postgresql
  encoding:  utf8
  username:
  password:
  pool:      2
  timeout:   5000
  database: edge-yl_development

test:
  <<: *default
  database: edge-yl_test
